Repository shadow/tornettools, pull requests merged in 2021-08, with the labels that each got.

#30 Exit gracefully on KeyboardInterrupt
  tornettools/simulate.py
Labels: bug

#32 Refactor students t lookup, explain level math
  tornettools/plot_common.py
Labels: documentation, enhancement

#31 Support new graph and config formats used by shadow
  README.md
  tornettools/generate.py
  tornettools/stage.py
  tornettools/tornettools
  tornettools/util.py
Labels: enhancement
