Repository shadow/tornettools, pull requests merged in 2021-06, with the labels that each got.

#13 Workflow improvements
  .github/workflows/ci.yml
Labels: enhancement

#12 Fix filename of staging json in README
  README.md
Labels: documentation

#14 Fall back when capture_output is not supported
  tornettools/generate_tor.py
  tornettools/tornettools
Labels: bug

#16 Updated tor build instructions in README
  README.md
Labels: documentation

#17 Rearrange tor and tgen configuration files
  tornettools/generate.py
  tornettools/generate_defaults.py
  tornettools/generate_tgen.py
  tornettools/generate_tor.py
Labels: enhancement

#18 Tweak parallelism, add comment to torrc files
  tornettools/generate_tor.py
  tornettools/tornettools
Labels: documentation, enhancement

#20 Use integer division when calculating 'parallelism'
  tornettools/tornettools
Labels: bug
